# mise.toml

[tools]
node = "20"
npm = "latest"

[tasks.dev]
description = "Start a local server with live reload"
run = "npx live-server . --entry-file=index.html --watch=."

[tasks.dev-nocache]
description = "Start a local server with cache disabled"
run = "npx live-server . --entry-file=index.html --watch=. --headers 'Cache-Control: no-cache, no-store, must-revalidate'"
