name: Update Contributors

on:
  schedule:
    - cron: "0 0 * * *" # run once a week
  workflow_dispatch:      # allow manual trigger

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate contributors list
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const path = "README.md";

            // Fetch contributors via API
            const contributors = await github.paginate(
              github.rest.repos.listContributors,
              { owner: context.repo.owner, repo: context.repo.repo }
            );

            // Build Markdown table
            let table = "## Contributors ✨\n\nThanks goes to these wonderful people:\n\n<table><tr>\n";
            contributors.forEach((c, i) => {
              table += `
              <td align="center">
                <a href="${c.html_url}">
                  <img src="${c.avatar_url}" width="100px;" alt="${c.login}"/>
                  <br />
                  <sub><b>${c.login}</b></sub>
                </a>
                <br />💻
              </td>`;
              if ((i + 1) % 6 === 0) table += "\n</tr><tr>\n";
            });
            table += "\n</tr></table>\n";

            // Read README, replace section between markers
            let readme = fs.readFileSync(path, "utf8");
            const start = "<!-- CONTRIBUTORS-START -->";
            const end = "<!-- CONTRIBUTORS-END -->";
            const regex = new RegExp(`${start}[\\s\\S]*${end}`);
            const replacement = `${start}\n${table}\n${end}`;
            if (readme.match(regex)) {
              readme = readme.replace(regex, replacement);
            } else {
              readme += `\n\n${replacement}`;
            }

            fs.writeFileSync(path, readme);
            console.log("Contributors section updated!");

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update contributors list" || echo "No changes to commit"
          git push
