# .github/workflows/welcome.yml

name: Welcome First-Timers

on:
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome new contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Hey @${{ github.actor }}! 🎉 Thank you so much for your first contribution to Developer's Toolkit! We're thrilled to have you here.

            I'll review your pull request as soon as possible. Meanwhile, feel free to check out other issues.

            Welcome to the community! 🚀